apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: cf
  name: rollout-reporter
  namespace: staging-runtime-12-05-eti-local-cluster
spec:
  eventBusName: codefresh-eventbus
  resource:
    analysisruns:
      eventTypes:
      - ADD
      - UPDATE
      - DELETE
      filter:
        createdBy: null
      group: argoproj.io
      namespace: staging-runtime-12-05-eti-local-cluster
      resource: analysisruns
      version: v1alpha1
    replicasets:
      eventTypes:
      - ADD
      - UPDATE
      - DELETE
      filter:
        createdBy: null
      group: apps
      namespace: staging-runtime-12-05-eti-local-cluster
      resource: replicasets
      version: v1
    rollouts:
      eventTypes:
      - ADD
      - UPDATE
      - DELETE
      filter:
        createdBy: null
      group: argoproj.io
      namespace: staging-runtime-12-05-eti-local-cluster
      resource: rollouts
      version: v1alpha1
  template:
    container:
      name: ""
      resources: {}
    serviceAccountName: rollout-reporter-sa
status: {}
